function(deploy_cuda_dependencies TARGET_NAME COMPONENTS)
    set(TARGET_DEPENDENCIES_COMMON ${COMPONENTS})
    set(TARGET_DEPENDENCIES_DEBUG "")
    set(TARGET_DEPENDENCIES_RELEASE "")
    list(TRANSFORM TARGET_DEPENDENCIES_COMMON APPEND "64_${CUDA_VERSION_MAJOR}")
	if (CUDA_VERSION_MAJOR EQUAL 11)
		list(TRANSFORM TARGET_DEPENDENCIES_COMMON REPLACE "cudart64_${CUDA_VERSION_MAJOR}"
														  "cudart64_${CUDA_VERSION_MAJOR}0")
		# cufft is at version 10 for CUDA 11.8
		list(TRANSFORM TARGET_DEPENDENCIES_COMMON REPLACE "cufft64_${CUDA_VERSION_MAJOR}" "cufft64_10")
		list(TRANSFORM TARGET_DEPENDENCIES_COMMON REPLACE "curand64_${CUDA_VERSION_MAJOR}" "curand64_10")												
	elseif(CUDA_VERSION_MAJOR EQUAL 12)		
		# cufft is at version 11 for CUDA 12
		list(TRANSFORM TARGET_DEPENDENCIES_COMMON REPLACE "cufft64_${CUDA_VERSION_MAJOR}" "cufft64_11")
		list(TRANSFORM TARGET_DEPENDENCIES_COMMON REPLACE "curand64_${CUDA_VERSION_MAJOR}" "curand64_11")
	elseif(CUDA_VERSION_MAJOR EQUAL 13)		
		# cufft is at version 11 for CUDA 12
		list(TRANSFORM TARGET_DEPENDENCIES_COMMON REPLACE "cufft64_${CUDA_VERSION_MAJOR}" "cufft64_12")
		list(TRANSFORM TARGET_DEPENDENCIES_COMMON REPLACE "curand64_${CUDA_VERSION_MAJOR}" "curand64_10")	
	endif()
    list(TRANSFORM TARGET_DEPENDENCIES_COMMON APPEND ".dll")
	if(CUDA_VERSION_MAJOR EQUAL 13)		
	#todo: winarm64
		list(TRANSFORM TARGET_DEPENDENCIES_COMMON PREPEND "${CUDAToolkit_BIN_DIR}/x64/")
	else()
		list(TRANSFORM TARGET_DEPENDENCIES_COMMON PREPEND "${CUDAToolkit_BIN_DIR}/")
	endif()
    

    deploy_dependencies(${TARGET_NAME} "${TARGET_DEPENDENCIES_COMMON}" "${TARGET_DEPENDENCIES_DEBUG}"
                        "${TARGET_DEPENDENCIES_RELEASE}")
endfunction()
