function(add_optimization_flags TARGET_NAME)    
    if (MSVC)        
        if (${CMAKE_HOST_SYSTEM_PROCESSOR} STREQUAL "AMD64")
            target_compile_options(${TARGET_NAME} PRIVATE $<$<COMPILE_LANGUAGE:CXX>:/arch:AVX2>)
        endif()
        if (${CMAKE_HOST_SYSTEM_PROCESSOR} STREQUAL "ARM64")
            target_compile_options(${TARGET_NAME} PRIVATE $<$<COMPILE_LANGUAGE:CXX>:/arch:armv8.2>)         
        endif()
    endif()
    if (UNIX)             
        #build for native host architecture  for maximum performance (might not work on all systems)   
        #works both for x86_64 and aarch64                
            target_compile_options(${TARGET_NAME} PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-march=native>)
    endif()
endfunction()