name: CMake on Linux (ARM64)
'on':
  pull_request:
    branches:
      - main
      - 54-add-a-runtime-compilation-version-of-the-library-for-nvidia-gpus
jobs:
  build:
    runs-on:
      - self-hosted
      - linux
      - arm64
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Release
        cpp_compiler:
          - g++
          - clang++
    steps:
      - uses: actions/checkout@v4
      - name: Add to PATH
        shell: bash
        run: |
          echo "/usr/lib/llvm-19/bin" >> $GITHUB_PATH
      - name: Set reusable strings
        id: strings
        run: >
          echo "build-output-dir=${{github.workspace}}/build" >>
          "$GITHUB_OUTPUT"        
      - name: Configure CMake
        run: >
          cmake -G "Unix Makefiles" -B
          ${{steps.strings.outputs.build-output-dir}}
          -DCMAKE_CXX_COMPILER=${{matrix.cpp_compiler}}        
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}}  -DCUDA_ARCH="87;"        -S
          ${{github.workspace}};        
      - name: Build
        run: >
          core_count=$(nproc) cmake --build ${{
          steps.strings.outputs.build-output-dir }}  --config ${{
          matrix.build_type }} --parallel $core_count
                       
      - name: Test
        working-directory: '${{ steps.strings.outputs.build-output-dir }}'
        run: >-
          ctest --build-config ${{ matrix.build_type }} --output-junit
          test_results.xml
