name: 'CMake on Windows (x64 host, ARM64 build)'
'on':
  pull_request:
    branches:
      - main
      - 54-add-a-runtime-compilation-version-of-the-library-for-nvidia-gpus
jobs:
  build:
    runs-on:
      - self-hosted
      - windows
      - x64
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Release
        toolset:
          - 'v143,cuda=12.9'
        cpp_compiler:
          - cl
    steps:
      - uses: actions/checkout@v4
      - name: Set reusable strings
        id: strings
        run: >
          echo "build-output-dir=${{github.workspace}}/build" >>
          "$env:GITHUB_OUTPUT"        
             
      - name: Configure CMake
        run: >
          $vsWhere = "${Env:ProgramFiles(x86)}\Microsoft Visual
          Studio\Installer\vswhere.exe"   

          $vsInstallationPath = & $vsWhere -products * -latest -property
          installationPath

          & "${vsInstallationPath}\Common7\Tools\Launch-VsDevShell.ps1" -Arch
          arm64 -HostArch amd64 -SkipAutomaticLocation                

          cmake -G "Visual Studio 17 2022"  -DENABLE_CUDA=OFF -B
          ${{steps.strings.outputs.build-output-dir}}
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -T ${{matrix.toolset}} -S
          ${{github.workspace}};        
      - name: Build
        run: >
          $poolsize=$env:NUMBER_OF_PROCESSORS/1;
          $vsWhere = "${Env:ProgramFiles(x86)}\Microsoft Visual
          Studio\Installer\vswhere.exe"   

          $vsInstallationPath = & $vsWhere -products * -latest -property
          installationPath

          & "${vsInstallationPath}\Common7\Tools\Launch-VsDevShell.ps1" -Arch
          arm64 -HostArch amd64 -SkipAutomaticLocation         
          
          cmake --build ${{ steps.strings.outputs.build-output-dir }} --config
          ${{ matrix.build_type }} --parallel  $poolsize
            
          #note, we cannot test as we don't hava a windows arm64 host yet
        working-directory: '${{ steps.strings.outputs.build-output-dir }}'
